name: PlayerVaults
authors: [drtshock, kashike, mbaxter]
website: ${project.url}
version: ${project.version}
main: com.drtshock.playervaults.PlayerVaults
softdepend: [Vault, Multiverse-Inventories, PlaceholderAPI]
api-version: 1.21

permissions:
  playervaults.admin:
    description: Grants access to admin commands for vaults.
    default: op
  playervaults.bypassblockeditems:
    description: Grants access to bypass blocked vault items.
    default: op
  playervaults.commands.use:
    description: Use the command
    default: true
